apiVersion: "v1"
kind: "Pod"
metadata:
  name: jacoku-testee-a-b
  annotations:
    jacoco/enable: 'True'
    jacoco/git-commit: 92d05402fc70477b02572a87987d4030b86e85e5
    jacoco/git-url: https://github.com/guohai163/jacoku-testee.git
spec:
  containers:
    - name: "jacoku-testee"
      image: "ghcr.io/guohai163/jacoku-testee:later"
      env:
        - name: JAVA_OPTS
          value: "-javaagent:/opt/java-agent/org.jacoco.agent-runtime.jar=output=tcpserver,address=*,append=true"